services:
    postgres:
        image: postgres:alpine
        container_name: stedi-postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '${POSTGRES_PORT:-5432}:5432'
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-stedi}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-stedipassword}
        networks:
            - app-network

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
